#1
moco2-t/menutable pull request #2
Opened 2021-05-23 02:23 UTC by moco2-t

## resipe登録ページ
　 URL用のform作成
 　注意書き作成
　 recipe/テーブルに保存（登録）
 　保存後recipe/ingredientを表示
 　エラーメッセージの表示
 　recipe一覧 (/recipes/index)リンク作成
 　自分で入力( /recipes/self_new)のリンク作成
## ingredientの入力ページ
　form作成
　セレクトボックスの作成
　 テーブルに保存（登録）
 　保存後recipe/ingredientを表示
 　エラーメッセージの表示
すでにshow,editなども追記してしまっていた

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +def recipe
これはどこかで呼び出されていますか?

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    @create_recipe = Recipe.new(
`create_recipe`だと、「レシピを作成する」という意味になるので、「作成されたレシピ」であれば、たとえば`created_recipe`にした方が適切かとおもいます

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +def ingredient
Rails(ActionController)によって予め定義されている、`index`や`create`や`show`といったメソッド以外の、独自で定義するメソッドについては、`private`に寄せるほうが、可読性や意図しない公開を避けられる点で良いかとおもいます。
https://docs.ruby-lang.org/ja/latest/method/Module/i/private.html

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    doc = Nokogiri::HTML.parse(html) #取得したhtmlをNokogiriでパースする
createメソッドとingredientメソッドで同様の実装があるので、「urlを与えられると、Nokogiriでパースする」に閉じたメソッドを定義して共通化しておくともしかしたらよいかもしれません。

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    if @new_food.save
`new_food`のスコープはこのメソッドで閉じているようにみえます。インスタンス変数にする特別な必要がありましたか?

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +def update_ingredient
現状どこからも参照されることがなければ、除いてください(残す必要があれば、その旨をコメントで記述しておいてください)

2021-05-23 11:51 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +#render plain: params.inspect paramsの内容確認
このコメントは削除してよいものですか?

2021-05-23 12:05 UTC, hrfmmr commented
@moco2-t コメントしました!

2021-05-24 06:18 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +def update_ingredient
updateで使用します

2021-05-24 06:18 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +#render plain: params.inspect paramsの内容確認
すみません、削除しました！

2021-05-24 06:20 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +    if @new_food.save
いや、特にないです。変数に変更しました。

2021-05-24 06:20 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +    @create_recipe = Recipe.new(
`created_recipe` に変更しました

2021-05-24 06:20 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +def recipe
`def update`で使用する予定で書いた物だと思います。

2021-05-24 09:01 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +def recipe
なるほど、ちなみに、`def update`は本PRに含まれるものでしたか?(もし含まれないのであれば、PRに含めなくてよいかとおもいます)

2021-05-24 09:02 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    @create_recipe = Recipe.new(
変更が反映されているcommitもpushしてこのthread上に貼っておいてくださいー

2021-05-24 09:02 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    if @new_food.save
変更が反映されているcommitもpushしてこのthread上に貼っておいてくださいー

2021-05-25 06:48 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +def ingredient
可読性や意図しない公開を避けられることによって何が良いのかよくわからない・・・

private に設定されたメソッドは関数形式でしか呼び出せないから、viewファイルに書くとき手間に感じる。
それでも可読性や意図しない公開を避けられる点ではやっておいほうがいいのか？
https://26gram.com/private-protected-in-ruby

2021-05-27 02:16 UTC, moco2-t commented
## #1-add_helpermethod　確認お願いします。

2021-05-27 02:33 UTC, hrfmmr reviewed
追加でコメントしました。helperに寄せられる箇所は寄せられていて良いとおもいます。
ちなみに、[ここ](https://github.com/moco2-t/menutable/pull/2/files#r637714541)や[ここ](https://github.com/moco2-t/menutable/pull/2/files#r637714509)に関するcommitがpushされていないようです。確認してみてくださいー

2021-05-27 02:33 UTC, hrfmmr commented on app/helpers/recipe_helper.rb
> +        #scraping_amount = doc.css('.ingredient_quantity')
不要であればコメントは削除してよいかとおもいます

2021-05-27 02:33 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +
末尾空行は消してよいかとおもいます。(ここ以外のも見直してみてくださいー)

2021-05-27 03:51 UTC, moco2-t commented
controllerが漏れてました。確認お願いします。

2021-05-27 04:47 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +def ingredient
この `ingredient`は使われていない..?

2021-05-27 04:47 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    if @new_food.save
pushされてない..?

2021-05-27 13:26 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +def recipe
recipe_helperを使うことにしたので不要になったためdef recipeは削除しました
bea4a32

2021-05-27 13:28 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +    @create_recipe = Recipe.new(
created_recipeに変更しました
b0a8b76

2021-05-27 13:30 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +def ingredient
def ingredient はactionです。

2021-05-27 13:32 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +    doc = Nokogiri::HTML.parse(html) #取得したhtmlをNokogiriでパースする
recipe_helperに寄せました
bea4a32

2021-05-27 13:33 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +    if @new_food.save
b0a8b76

2021-05-27 13:40 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +def update_ingredient
updateは#1に関係ないので削除しました
b0a8b76

2021-05-27 13:41 UTC, moco2-t commented on app/helpers/recipe_helper.rb
> +        #scraping_amount = doc.css('.ingredient_quantity')
不要なので削除しました

2021-05-27 13:42 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +
不要なので削除しました
b0a8b76

2021-05-27 14:03 UTC, moco2-t commented on app/helpers/recipe_helper.rb
> +        #scraping_amount = doc.css('.ingredient_quantity')
e4fde02

2021-05-27 23:57 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    require 'kconv'
`require` はclass内ではなくソースファイルの先頭に記述してください

2021-05-27 23:58 UTC, hrfmmr requested changes

2021-05-27 23:58 UTC, hrfmmr commented on app/controllers/recipe_controller.rb
> +    require 'kconv'
`require` はclass内ではなくソースファイルの先頭に記述してください

2021-05-28 00:56 UTC, moco2-t commented on app/controllers/recipe_controller.rb
> +    require 'kconv'
そもそもcontrollerでは不要なので削除しました
da12733

2021-05-28 01:37 UTC, moco2-t commented
Changes requestedで指摘された部分変更しました。
2a61f77

db/migrate/20210520134802_create_foods.rb
db/migrate/20210521015532_create_ingredients.rb
この２つは必要ないと思ったのでローカル上ですでに削除してました。

2021-05-28 04:36 UTC, hrfmmr approved these changes
LGTM

2021-05-28 05:02 UTC, merged